# =============================================================================
# machine_learning.smk  —  pretreatment response prediction (modality comparison)
# -----------------------------------------------------------------------------
#
#   ml_prepare_data   dds.Rds + se.Rds        -> feature matrices + labels.csv
#   ml_train          feature matrix + labels -> per-(modality,model,k) folds
#   ml_aggregate      all fold CSVs           -> summary tables + plots
# =============================================================================

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

_ml = config["machine_learning"]

# modality -> output generated by ml_prepare_data
ML_DATA_FILE = {
    "TX_BINF": "output/machine_learning/data/TX_BINF_RvNR_W0_data.csv",
    "TX_PB": "output/machine_learning/data/TX_PB_RvNR_W0_data.csv",
    "PX_BINF": "output/machine_learning/data/PX_BINF_RvNR_W0_data.csv",
    "PX_PB":   "output/machine_learning/data/PX_PB_RvNR_W0_data.csv",
}

ML_RESULTS = expand(
    "output/machine_learning/raw/{modality}_{model}_k{k}.csv",
    modality=_ml["modalities"],
    model=_ml["models"],
    k=_ml["k_values"],
)

rule ml_prepare_data:
  input:
    dds_rds="output/rnaseq/dds/dds.Rds",
    se_rds="output/olink/se/se.Rds",
  output:
    labels_csv="output/machine_learning/data/RvNR_W0_labels.csv",
    tx_binf_rvnr_w0_data_csv="output/machine_learning/data/TX_BINF_RvNR_W0_data.csv",
    tx_pb_rvnr_w0_data_csv="output/machine_learning/data/TX_PB_RvNR_W0_data.csv",
    px_binf_rvnr_w0_data_csv="output/machine_learning/data/PX_BINF_RvNR_W0_data.csv",
    px_pb_rvnr_w0_data_csv="output/machine_learning/data/PX_PB_RvNR_W0_data.csv",
  params:
    ml_params=_ml,
  log:
    "output/machine_learning/data/ml_prepare_data.log",
  conda:
    "../envs/r-deseq2.yaml"
  message:
    "--- Preparing ML feature data matrices and labels ---"
  threads: 1
  resources:
    mem_mb=16000,
    runtime=1440,
    slurm_partition="defq",
  script:
    "../scripts/machine_learning/prepare_data.R"

rule ml_train:
  input:
    data=lambda wc: f"{ML_DATA_FILE[wc.modality]}",
    labels=rules.ml_prepare_data.output.labels_csv,
  output:
    folds_csv="output/machine_learning/raw/{modality}__{model}__k{k}.csv",
    feature_usage_csv="output/machine_learning/feature_selection/{modality}__{model}__k{k}__feature_usage.csv",
  params:
    _ml=config["machine_learning"],
    modality=lambda wc: wc.modality,
    model=lambda wc: wc.model,
    k=lambda wc: int(wc.k),
    metric=_ml["metric"],
    n_seeds=_ml["n_seeds"],
    seed=_ml["seed"],
    tpot=_ml["tpot"],
  log:
    "output/machine_learning/raw/logs/{modality}__{model}__k{k}.log",
  conda:
    "../envs/machine_learning.yaml"
  message:
    "--- ML train: {wildcards.modality} / {wildcards.model} / k={wildcards.k} ---"
  threads: 1
  resources:
    mem_mb=32000,
    runtime=1440,
    slurm_partition="defq",
  script:
    "../scripts/machine_learning/train_model.py"


rule ml_aggregate:
    input:
        folds=expand(
            "output/machine_learning/raw/{modality}__{model}__k{k}.csv",
            modality=_ml["modalities"], model=_ml["models"], k=_ml["k_values"],
        ),
        features=expand(
            "output/machine_learning/feature_selection/{modality}__{model}__k{k}__feature_usage.csv",
            modality=_ml["modalities"], model=_ml["models"], k=_ml["k_values"],
        ),
    output:
        aggregated="output/machine_learning/summary/aggregated_predictions.csv",
        repeat_auc="output/machine_learning/summary/repeat_auc.csv",
        summary_by_k="output/machine_learning/summary/summary_by_k.csv",
        summary_best_k="output/machine_learning/summary/summary_best_k.csv",
        paired="output/machine_learning/summary/summary_paired_intersection.csv",
        pairwise="output/machine_learning/summary/summary_pairwise_bootstrap.csv",
        ranking="output/machine_learning/summary/summary_modality_ranking.csv",
        feature_summary="output/machine_learning/summary/feature_usage_summary.csv",
        plots=directory("output/machine_learning/summary/plots"),
    params:
        modalities=_ml["modalities"],
        models=_ml["models"],
        k_values=_ml["k_values"],
        seed=int(_ml["seed"]),
        n_boot=int(_ml.get("n_boot", 2000)),
        top_n_features=int(_ml.get("top_n_features", 25)),
    log:
        "output/machine_learning/summary/aggregate_results.log",
    conda:
        "../envs/machine_learning.yaml"
    threads: 1
    resources:
        mem_mb=8000,
        runtime=1440,
        slurm_partition="defq",
    message:
        "--- Aggregate ML results and generate plots ---"
    script:
        "../scripts/machine_learning/aggregate_results.py"